kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: blog-content
  annotations:
    volume.beta.kubernetes.io/storage-class: [STORAGE-CLASS-NAME]
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
